//===- ScheduleOptimizer.cpp - Optimize an ISL schedule with Pluto.-----======//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
//
//===----------------------------------------------------------------------===//

#include "polly/Test/ScheduleOptimizer.h"
#include "polly/JSONExporter.h"
#include "polly/Options.h"
#include "polly/Test/OpenSCoPExporter.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <cstdio>
#include <fstream>
#include <osl/scop.h>
#include <string>

using namespace llvm;
using namespace polly;

#define DEBUG_TYPE "polly-pluto"

static cl::opt<std::string> PlutoPath("polly-pluto-path",
                                      cl::desc("Pluto path"), cl::Hidden,
                                      cl::ValueRequired, cl::init(""),
                                      cl::cat(PollyCategory));

static cl::opt<std::string> PlutoArguments(
    "polly-pluto-args", cl::desc("Arguments to be passed to pluto optimizer"),
    cl::Hidden, cl::ValueRequired,
    cl::init("--tile --nodiamond-tile --nointratileopt --parallel"),
    cl::cat(PollyCategory));

namespace {

std::string exec(const char *Command) {
  std::array<char, 512> Buffer;
  std::string Result;

  std::unique_ptr<FILE, decltype(&pclose)> Pipe(popen(Command, "r"), pclose);

  if (!Pipe)
    report_fatal_error("PlutoScheduleOptimizerPass: popen() failed!");

  while (fgets(Buffer.data(), Buffer.size(), Pipe.get()) != nullptr) {
    Result += Buffer.data();
  }

  return Result;
}

std::string extractOpenScopFromString(std::string &Input) {
  size_t Start = Input.find("# [File generated by the OpenScop Library");
  size_t End = Input.find("</OpenScop>");
  End += std::string("</OpenScop>").size();

  return Input.substr(Start, End - Start);
}

void saveToFile(const std::string &Filename, const std::string &Content) {
  std::ofstream Outfile(Filename);
  if (!Outfile) {
    std::string Msg = "PlutoScheduleOptimizerPass: Could not open file " +
                      Filename + " for writing!";
    report_fatal_error(Msg.c_str());
  }

  Outfile << Content;
  Outfile.close();
}
} // namespace

void polly::runPlutoScheduleOptimizer(Scop &S) {
  LLVM_DEBUG(errs() << "PlutoScheduleOptimizerPass run on " << S.getName()
                    << "\n");

  std::string FileNameInput = "./" + getFileName(S, "_input", "scop");

  OpenSCoPExportPass::exportOpenScop(S, FileNameInput);

  LLVM_DEBUG(errs() << "Calling pluto on the file " << FileNameInput << "\n");

  if (PlutoPath.empty()) {
    std::string CopyCommand =
        "docker cp " + FileNameInput + " pluto_container:/home/";
    LLVM_DEBUG(errs() << "CopyCommand: " << CopyCommand << "\n");
    std::system(CopyCommand.c_str());
  }
  std::string RunPlutoCommand;

  if (PlutoPath.empty()) {
    RunPlutoCommand = "docker exec pluto_container sh -c \"cat /home/" +
                      FileNameInput + " | pluto " + PlutoArguments +
                      " --readscop stdin -o stdout\"";
  } else {
    RunPlutoCommand = "cat ./" + FileNameInput + " | " + PlutoPath + " " +
                      PlutoArguments + " --readscop stdin -o stdout";
  }
  LLVM_DEBUG(errs() << "RunPlutoCommand: " << RunPlutoCommand << "\n");
  auto ResultPluto = exec(RunPlutoCommand.c_str());

  LLVM_DEBUG(errs() << "Result of pluto:\n" << ResultPluto << "\n");

  std::string NewScopExtracted = extractOpenScopFromString(ResultPluto);

  std::string FileNameOutput = getFileName(S, "_output", "scop");
  saveToFile(FileNameOutput, NewScopExtracted);

  OpenSCoPImportPass::importOpenScop(S, FileNameOutput, FileNameInput);

  LLVM_DEBUG(errs() << "PlutoScheduleOptimizerPass done\n");
}

PreservedAnalyses
PlutoScheduleOptimizerPass::run(Scop &S, ScopAnalysisManager &SAM,
                                ScopStandardAnalysisResults &SAR,
                                SPMUpdater &U) {
  LLVM_DEBUG(errs() << "PlutoScheduleOptimizerPass run on " << S.getName()
                    << "\n");

  std::string FileNameInput = "./" + getFileName(S, "_input", "scop");

  OpenSCoPExportPass::exportOpenScop(S, FileNameInput);

  LLVM_DEBUG(errs() << "Calling pluto on the file " << FileNameInput << "\n");

  if (PlutoPath.empty()) {
    std::string CopyCommand =
        "docker cp " + FileNameInput + " pluto_container:/home/";
    LLVM_DEBUG(errs() << "CopyCommand: " << CopyCommand << "\n");
    std::system(CopyCommand.c_str());
  }
  std::string RunPlutoCommand;

  if (PlutoPath.empty()) {
    RunPlutoCommand = "docker exec pluto_container sh -c \"cat /home/" +
                      FileNameInput + " | pluto " + PlutoArguments +
                      " --readscop stdin -o stdout\"";
  } else {
    RunPlutoCommand = "cat ./" + FileNameInput + " | " + PlutoPath + " " +
                      PlutoArguments + " --readscop stdin -o stdout";
  }
  LLVM_DEBUG(errs() << "RunPlutoCommand: " << RunPlutoCommand << "\n");
  auto ResultPluto = exec(RunPlutoCommand.c_str());

  LLVM_DEBUG(errs() << "Result of pluto:\n" << ResultPluto << "\n");

  std::string NewScopExtracted = extractOpenScopFromString(ResultPluto);

  std::string FileNameOutput = getFileName(S, "_output", "scop");
  saveToFile(FileNameOutput, NewScopExtracted);

  OpenSCoPImportPass::importOpenScop(S, FileNameOutput, FileNameInput);

  LLVM_DEBUG(errs() << "PlutoScheduleOptimizerPass done\n");

  return PreservedAnalyses::none();
}
